SNOWFLAKE ACCOUNT FUNCTIONS AND PROCEDURES;

CREATE OR REPLACE FUNCTION TEST_DATA_DB.TEST_DATA_SCHEMA.AREA_OF_CIRCLE("RADIUS" FLOAT)
RETURNS FLOAT
LANGUAGE SQL
AS '
    pi() * radius * radius
  ';
  
  
  
CREATE OR REPLACE FUNCTION TEST_DATA_DB.TEST_DATA_SCHEMA.SALES_QUANTITY()
RETURNS TABLE ("SALESORDERNUMBER" VARCHAR(255), "SUM_QUANTITY" NUMBER(38,0))
LANGUAGE SQL
AS '
    select salesordernumber,sum(quantity) from test_data_db.test_data_schema.sales group by salesordernumber having sum(quantity)>100
  ';
  

CREATE OR REPLACE FUNCTION TEST_DATA_DB.TEST_DATA_SCHEMA.YEARLY_SALES()
RETURNS TABLE ("YEAR" NUMBER(38,0), "COUNT" NUMBER(38,0))
LANGUAGE SQL
AS '
    SELECT DATE_PART(YEAR,TO_DATE(ORDERDATE)),COUNT(salesordernumber)  FROM SALES GROUP BY DATE_PART(YEAR,TO_DATE(ORDERDATE))
';


CREATE OR REPLACE PROCEDURE TEST_DATA_DB.TEST_DATA_SCHEMA.SALES_QUANTITY_ORDER()
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
  BEGIN
    select salesordernumber from test_data_db.test_data_schema.sales group by salesordernumber having sum(quantity)>100;
    END;
  ';
  
  
