USE SCHEMA DEMO_SCHEMA;

create or replace TABLE SALESPERSON (
	EMPLOYEEKEY NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	SALESPERSON VARCHAR(1000),
	TITLE VARCHAR(255),
	UPN VARCHAR(255)
);

create or replace TABLE STUDENT (
	STUDENTID NUMBER(38,0),
	STUDENTNAME VARCHAR(255),
	BRANCH VARCHAR(255)
);

create or replace TABLE TARGETS (
	EMPLOYEEID NUMBER(38,0),
	TARGET VARCHAR(255),
	TARGETMONTH VARCHAR(255)
);

ALTER TABLE ORGANIZATIONS MODIFY INDEX NUMBER(38,0);

ALTER TABLE PRODUT RENAME TO PRODUCT;

ALTER TABLE REGION ADD COLUMN REGION_NO INTEGER  DEFAULT 9999;

ALTER TABLE RESELLER ADD COLUMN CITY_CODE VARCHAR(255);

UPDATE RESELLER
SET CITY_CODE=SUBSTR(CITY,1,3);

ALTER TABLE REGION MODIFY COUNTRY VARCHAR(255) NOT NULL;